// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Repository.Models
{
    public partial class CheckList
    {
        public Guid CheckId { get; set; }
        public Guid TaskId { get; set; }
        [Required]
        [StringLength(100)]
        public string ToDo { get; set; }
        public bool? IsCompleted { get; set; }
        public bool? IsDeleted { get; set; }

        [ForeignKey("TaskId")]
        [InverseProperty("CheckList")]
        public virtual Task Task { get; set; }
    }
}